name: Dump API data

on:
  schedule:
    - cron: "0 12 * * FRI" # At 12:00 on Friday.
  workflow_dispatch:

env:
  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
  HOMARR_CROWDIN_TOKEN: "${{ secrets.HOMARR_CROWDIN_TOKEN }}"
  HOMARR_LABS_CROWDIN_TOKEN: "${{ secrets.HOMARR_LABS_CROWDIN_TOKEN }}"

permissions:
  contents: write

jobs:
  dump:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm run api-dump-contributors
      - uses: EndBug/add-and-commit@v9
        with:
          add: './static'
          default_author: github_actor
          message: '(chore): update contributors'
          push: true